import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { generateReferralCode } from '@/lib/referrals';
const schema = z.object({ email: z.string().email().transform((v) => v.toLowerCase()), password: z.string().min(8).max(128), name: z.string().trim().min(2).max(80), referralCode: z.string().regex(/^[a-zA-Z0-9_-]{2,64}$/).optional() });
export async function POST(req: NextRequest) { try { if (await getServerSession(authOptions)) return NextResponse.json({ error: 'Vous êtes déjà connecté.' }, { status: 400 }); const input = schema.parse(await req.json()); const bonus = 10; const passwordHash = await bcrypt.hash(input.password, 12); const influencer = input.referralCode ? await prisma.influencer.findFirst({ where: { referralCode: input.referralCode.toUpperCase(), active: true } }) : null; const user = await prisma.$transaction(async (tx) => { const created = await tx.user.create({ data: { email: input.email, name: input.name, passwordHash, referralCode: generateReferralCode(), influencerId: influencer?.id, creditBalance: bonus, creditsEarned: bonus, creditsGranted: bonus } }); await tx.creditTransaction.create({ data: { userId: created.id, type: 'signup_bonus', amount: bonus, description: 'Bonus de bienvenue', referenceId: created.id } }); if (influencer) await tx.referral.create({ data: { userId: created.id, influencerId: influencer.id, sourceCode: input.referralCode!.toUpperCase(), expiresAt: new Date(Date.now() + 30 * 86400000) } }); return created; }); return NextResponse.json({ success: true, user: { id: user.id, email: user.email } }, { status: 201 }); } catch (error) { if (error && typeof error === 'object' && 'code' in error && error.code === 'P2002') return NextResponse.json({ error: 'Cette adresse e-mail est déjà utilisée.' }, { status: 409 }); return NextResponse.json({ error: 'Données invalides ou serveur indisponible.' }, { status: 400 }); } }
